name: Deploy Pacedream website

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  login-into-server:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: ssh connection
        uses: appleboy/ssh-action@master
        with:
          host: 132.226.122.105
          username: ubuntu
          key: ${{ secrets.SSHSECRET }}
          port: 22
          script: |
            sudo su
            cd /webapps/gcohs/pacedream.com
            git config --global --add safe.directory /webapps/gcohs/pacedream.com
            git status
            pwd        
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
